import { Router } from "express";
import { verifyJWT } from "../middlewares/auth.middlewares.js";
import { addVideoToPlaylist, createPlaylist, deletePlaylist, getUserPlaylist, removeVideoFromPlaylist, updatePlaylist } from "../controllers/playlist.controller.js";

const router = Router();

router.route('/create').post(verifyJWT,createPlaylist);
router.route('/viewplaylist').post(verifyJWT,getUserPlaylist);
router.route('/getplaylist/:id').post(verifyJWT, getUserPlaylist);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
router.route('/addvideo/:id').post(verifyJWT, addVideoToPlaylist);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
router.route('/removevideo/:id').post(verifyJWT, removeVideoFromPlaylist);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
router.route('/removeplaylist/:id').post(verifyJWT, deletePlaylist);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
router.route('/updateplaylist/:id').post(verifyJWT, updatePlaylist);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

export default router;