import { Router } from "express";
import { verifyJWT } from "../middlewares/auth.middlewares.js";
import { addVideoToPlaylist, createPlaylist, getUserPlaylist, removeVideoFromPlaylist } from "../controllers/playlist.controller.js";

const router = Router();

router.route('/create').post(verifyJWT,createPlaylist);
router.route('/viewplaylist').post(verifyJWT,getUserPlaylist);
router.route('/getplaylist/:id').post(verifyJWT, getUserPlaylist);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
router.route('/addvideo/:id').post(verifyJWT, addVideoToPlaylist);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
router.route('/removevideo/:id').post(verifyJWT, removeVideoFromPlaylist);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

export default router;